#!/usr/bin/env bash

XDG_CONFIG_HOME="$HOME/.config"
XDG_CACHE_HOME="$HOME/.cache"
XDG_DATA_HOME="$HOME/.local/share"
XDG_STATE_HOME="$HOME/.local/state"

if [ -f "$XDG_CONFIG_HOME/user-dirs.dirs" ]; then
    source "$XDG_CONFIG_HOME/user-dirs.dirs"
fi

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

