matches:
  - trigger: ":fullname"
    replace: "{{output}}"
    vars:
      - name: output
        type: random
        params:
          choices:
            - "Stretch Oxford"
            - "Charcuteri Jones"
            - "Bangs McWeed"
            - "Sleeve McShirt"
            - "Hoff Isvibe"
            - "Keanu Takamehier"
            - "Herzog Cottontail"
            - "Bob Hotmail"
            - "Colon Buttersmud"
            - "Dan Crackleback"
            - "Ricky Circlechest"
            - "Myke Aars"
            - "Luba Derm"
            - "Rusty Dunes"
            - "Pen Talobe"
            - "Cloodles Gibsford"
            - "Barry Toes"
            - "Mike Rossbowe"
            - "Mike Rosoft"
            - "Jake Chillinall"
            - "Maggie Chillinall"
            - "Chris P. Bacon"
            - "Louis Futon"
            - "Sir Chingens"
            - "Mike Arrage"
            - "Dude Iligents"
            - "Anne Abler"
            - "Buff Mantooth"
            - "Reed Moore"
            - "James Circleback"
            - "Geöff Leopard"
            - "Vin Detail"
            - "Beef Lexible"
            - "Dirk Chirklette"
            - "Merk Chirklette"
            - "Kay Sowe"
            - "Khan Gress"
            - "Neve Stoodles"
            - "Drew Boxes"
            - "Franz Scheizing"
            - "Richard Dunngeon"
            - "Rick O’Shea"
            - "Pete Za"
            - "Atlas Chapman"
            - "Robbie Cinnamon"
            - "Richard Funk"
            - "Robert Sledd"
            - "Samuel Tsung"
            - "Ward Press"
            - "Jake Weary"
            - "Drew Pale"
            - "Rusty Foxglove"
            - "Dewey Tymesheets"
            - "Albert Dente"
            - "Phil Lander"
            - "Nick Hole"
            - "Lee Nard"
            - "Dee Leet"
            - "Vershon Kontroll"
            - "Shakira Underwood"
            - "Richard Trickle"
            - "Thicc Buffman"
            - "Miles Prower"
            - "Iqbal Achieve"
            - "Nina Armenian"
            - "Forrest Ash"
            - "Martin Aynuss"
            - "Kikini Bamalam"
            - "Dominic Bambercrunch"
            - "Whack Barnet"
            - "Danny Bear"
            - "Weech Beacon"
            - "Derek Bildings"
            - "Howard Blackcap"
            - "Bellender Bojangles"
            - "Cliff Bonanza"
            - "Jesus Bond"
            - "Charles Bonus"
            - "Cocka Boo"
            - "Kika Bright"
            - "Howard Bugowitz"
            - "Kate Card"
            - "Greta Cargo"
            - "Bennet Carnival"
            - "Mick Carriage"
            - "Scott Chestnut"
            - "Richard Chickentoss"
            - "Jill Clear"
            - "Duncan Clench"
            - "Sal Commotion"
            - "Romley Compton"
            - "Witch Conan"
            - "Rob Continental"
            - "Royce Coolidge"
            - "Colin Corknorth"
            - "Dickie Davies"
            - "Portia De Coogan"
            - "Dwight Difference"
            - "Neil Doobla-Decca"
            - "Ray Dooney"
            - "Sonny-Sam Dysco"
            - "Trevor Eev"
            - "Ben Egyptian"
            - "Harris Envy"
            - "Tony Excalibur"
            - "Hawk Fahrenheit"
            - "Clem Fandango"
            - "Mustafa Fasili"
            - "Kate Fear"
            - "Bob Fennison"
            - "Pinch Finga"
            - "Norris Flipjack"
            - "Milly Floss"
            - "Dennis Fog"
            - "Lord Fotheringham"
            - "Edward Fox"
            - "Dinky Frinkbuster"
            - "Dick Frippery"
            - "Beezus Fuffoon"
            - "Shane Fulorgy"
            - "Barry Fuqu"
            - "Jemima Gina"
            - "Max Gland"
            - "Colin Graveyard"
            - "Rusty Halloween"
            - "Jon Hamm"
            - "Chloe Hammersnag"
            - "Aya Hassan"
            - "Acker Herron"
            - "Roy Highnock"
            - "Pooky Hook"
            - "Champion House"
            - "Sookie Houseboat"
            - "Ed Howzer-Black"
            - "Brooke Hooberman"
            - "Axel Jacklin"
            - "Liberty Jerbil"
            - "Shepherd Jerbil"
            - "Basil Jet"
            - "Sorry Johnson"
            - "Hoop Kaaak"
            - "Bentley Kenneth"
            - "Daz Klondyke"
            - "Tycoon Lancaster"
            - "Candi Lee"
            - "Clint Legal"
            - "Kit Leggings"
            - "Una Length"
            - "Jennifyer Madraass"
            - "Joogie Makepiece"
            - "Varrity Map"
            - "Posh Dong Mingemuncher"
            - "Sola Mirrornek"
            - "Harriet Monkhound"
            - "Bob Monkhouse"
            - "Clancy Moped"
            - "Larry Muggins"
            - "Russ Nightlife"
            - "Warren Organ"
            - "Senna Paddington"
            - "Trevor Paradise"
            - "Jeremy Paxman"
            - "Kelsey Perfume"
            - "Parker Pipe"
            - "Sue Pipkins"
            - "Connie Plank"
            - "Jane Plough"
            - "Peggy Playwood"
            - "Eve Poldark"
            - "Linda Praise"
            - "Michael Prance"
            - "Cliff Promise"
            - "Daisy Prosper"
            - "Sue Prussia"
            - "Bill Purchase"
            - "Mrs Purchase"
            - "Ray Purchase"
            - "Heathcoat Pursuit"
            - "Jill Quear"
            - "Smooth Quiver"
            - "Giuseppe Race"
            - "Susan Random"
            - "Strawberry Rathbone"
            - "Baz Ravish"
            - "Hercule Razzamatazz"
            - "Warrior Regis"
            - "Collage Roy"
            - "Ormond Sacker"
            - "Carol Sass"
            - "Agent Saucepan"
            - "Kenton Schwepps"
            - "Ricky Seasack"
            - "Harold Shitman"
            - "Derek Sibling"
            - "Colin Skittles"
            - "Nan Slack"
            - "Ray Sober"
            - "Jenny Spasm"
            - "Julie St Burger"
            - "Frank Succession"
            - "Ken Suggestion"
            - "Nick Swivney"
            - "Billy Tarzana"
            - "Dennis Thwaites"
            - "Kate Tightneck"
            - "Vic Titball"
            - "Blair Toast"
            - "Ellen Toast"
            - "Gonville Toast"
            - "Paloma Toast"
            - "Steven Toast"
            - "Penny Traitor"
            - "Patrick Treble"
            - "Pool Turgid"
            - "Wander Us"
            - "Basil Watchfair"
            - "Church Weaver"
            - "Dick Weerdly"
            - "Cheryl Welk"
            - "Peanut Whistle"
            - "Des Wigwam"
            - "Phyliss Willis"
            - "Wil Willis"
            - "Yvonne Wryly"
            - "Lorna Wynde"
            - "Frank Zammer"
