#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#

# Dracula Scheme
BACKGROUND=0XFF282A36
CURRENTLINE=0XFF44475A
FOREGROUND=0XFFF8F8F2
COMMENT=0XFF6272A4
CYAN=0XFF8BE9FD
GREEN=0XFF50FA7B
ORANGE=0XFFFFB86C
PINK=0XFFFF79C6
PURPLE=0XFFBD93F9
RED=0XFFFF5555
YELLOW=0XFFF1FA8C

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist >/dev/null 2>&1 &

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_minimized action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"

$HOME/.config/yabai/create_spaces.sh

# BAR HEIGHT
BAR_HEIGHT=$(sketchybar -m --query bar | jq -r '.height')

yabai -m config external_bar all:40:0 \
	focus_follows_mouse off \
	mouse_follows_focus off \
	window_zoom_persist off \
	window_placement second_child \
	window_topmost off \
	window_shadow float \
	window_opacity on \
	window_opacity_duraction 0.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.9 \
	window_border on \
	window_border_width 3 \
	window_border_hidpi off \
	window_border_radius 11 \
	window_border_blur off \
	window_animation_duration 0.0 \
	active_window_border_color $PURPLE \
	normal_window_border_color $BACKGROUND \
	insert_feedback_color $COMMENT \
	split_ratio 0.50 \
	auto_balance on \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	top_padding 10 \
	bottom_padding 4 \
	left_padding 4 \
	right_padding 4 \
	window_gap 6

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|Photo Booth|Archive Utility|App Store|Raycast|Activity Monitor|Ubersicht)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref|Trash)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add label="Cisco AnyConnect Secure Mobility Client" app="Cisco AnyConnect Secure Mobility Client" manage=off

yabai -m config layout bsp
echo "yabai configuration loaded.."
