#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

export FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
export NERD_FONT="Liga SFMono Nerd Font"
PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $HOME/.config/sketchybar/helper && make)
$HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=45
  color=$BAR_COLOR
  border_width=2
  border_color=$BAR_BORDER_COLOR
  shadow=off
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  y_offset=-5
  margin=-2
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$PLUGIN_DIR/apple/item.sh"
source "$PLUGIN_DIR/spaces/item.sh"
source "$PLUGIN_DIR/yabai/item.sh"
source "$PLUGIN_DIR/front_app/item.sh"

# Center
source "$PLUGIN_DIR/spotify/item.sh"

# Right
source "$PLUGIN_DIR/calendar/item.sh"
#source "$PLUGIN_DIR/weather/item.sh"
#source "$PLUGIN_DIR/brew/item.sh"
#source "$ITEM_DIR/github.sh"
source "$PLUGIN_DIR/battery/item.sh"
source "$PLUGIN_DIR/bluetooth/item.sh"
source "$PLUGIN_DIR/wifi/item.sh"

source "$PLUGIN_DIR/volume/item.sh"
#source "$ITEM_DIR/cpu.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
